## Introduction to Deep Learning with Keras in R

**Instructor: Michał Maj (Appsilon Data Science)**

With the release of the R Keras package (https://keras.rstudio.com/) (by JJ Allaire and Francois Chollet) at the end of 2017 / beginning 2018 the topic of artificial neural networks and especially deep learning in R became red-hot within the R community.

In this workshop you will get answers for the following questions:

- What are fully conected and convolutional neural networks ?
- How to build a sequential model in Keras (keras_model_sequential() function) ?
- How to compile and fit naural netwrks in Keras (compile() and fit() functions) ?
- How to add regularization to neural networks (L1, L2, dropout) ?
- How to save and load existing models ?
- How to perform data ingestion and augmentation using generators ?
- How to use pre-trained models and perform fine-tuning ?
- How to use callbacks ?

Please make sure to bring your laptop including an up to date R version, RStudio and install Keras:

_Setup Keras (Make sure to install required prerequisites, before installing Keras using the commands below)_

```{r, eval=FALSE}
install_keras() # CPU version 
# install_keras(tensorflow = "gpu") # GPU version (recommended)
```


