## Jumping Rivers - Shiny Basics

**Instructor: Roman Popat (Jumping Rivers)**

a quick introduction to creating interactive visualisations of data using shiny. The workshop will first make sure everyone is familiar with rmarkdown and htmlwidgets for creating a document with nice visualisations. We will then extend this knowledge by examining the shiny package for creating input output bindings to interaction with our R data structures. We will cover the basics of input and output for a shiny application and then explore creating our own page layouts. By the end of the workshop participants should feel comfortable getting started with creating their own shiny applications. 

*recap/intro to markdown*

* a quick introduction/refresher on rmarkdown for document styling
* adding some interactive graphs through htmlwidgets

*input widgets and render functions*

* extend a markdown document to run using shiny
* adding input controls
* using inputs to render output tables and graphs

*page layouts using shiny and shiny dashboard*

* shiny and shinydashboard allow more control over page layouts
* creating a layout with input and output "slots"

