## Jumping Rivers - Advanced Shiny

**Instructor: Roman Popat (Jumping Rivers)**

This workshop would suit attendees who are already comfortable with creating shiny applications. We will explore how to add functionality to our app using javascript packages and code. No real javascript knowledge is required to get started if you are a confident R programmer but the session will contain examples with written javascript. We will then explore how one might deal with routines in a shiny application that take a long time to run, or how to provide a good experience for simultaneous users of your app. We will then explore creating a standalone web served API to our R code and integrate the use of it into a shiny application.

*adding functionality from javascript code*

* An introduction to using a javascript package with a shiny application
* the basics of passing javascript values to a shiny app as inputs


*futures and promises for long running code*

* An introduction to the wonderful promises package by rstudio's joe cheng
* promise pipes
* With some small changes to your app, stop long running tasks from blocking the main application

*create and integrate with an external API*

* Plumber is a great R package for creating a REST API on your R code and functions, we will explore how to get up and running with serving our R functions as an API
* Integrate our separate plumber API with our shiny app
