## iDash - Make your R slides awesome with xaringan

**Instructor: Mikołaj Olszewski & Mikołaj Bogucki (iDash)**

Preparing a slide deck with the results of your research seem to be quite straightforward. You produce all the plots and tables in R and just paste them into PowerPoint, right? Or you might have gone a bit further and already used RMarkdown with ioslides, Slidy or Beamer. Those technologies however have many drawbacks. Their default look is quite outdated and it’s hard to customise it and make each slide look exactly as you wanted. This might be especially problematic in case of companies that needs to follow strict brand guidelines.

This hands-on workshop will introduce participants to a different package called xaringan that solves all the issues. It allows to customise each slide entirely to suit needs of the most demanding users. Since it also uses RMarkdown, it allows to produce not only eye-catching but also reproducible results. Moreover, it allows to preview your slides dynamically in RStudio making your work much easier. It’s also relatively easy to export the slide deck (natively in HTML) to a pixel perfect PDF.

Join us if you want to learn how make your next R slide deck awesome!

## Preparation

We kindly ask participants to bring their own laptops with the following software installed:

- Recent version of R (at least 3.3)
- Recent version of RStudio (preferably the newest stable one)
- Recent version of Chrome (preferably the newest one)

R packages required for the workshops:

- xaringan (0.6)
- rmarkdown (1.10)
- leaflet
- plotly
- ggplot2
- DT

Those packages can be installed by running the following script:

```
install.packages("xaringan")
install.packages("rmarkdown")
install.packages("leaflet")
install.packages("plotly")
install.packages("ggplot2")
install.packages("DT")
```